apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  labels:
    app: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: api-container
          image: taskmanagementapp:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: TZ
              value: "Europe/Bucharest"
            - name: ConnectionStrings__RedisConnection
              value: "redis:6379"

            # 1. Parola DB din Secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: SQL_PASSWORD
            
            # 2. Connection String-ul principal
            - name: ConnectionStrings__DefaultConnection
              value: "Server=task-db-service;Database=TaskDB;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True;"
            
            # Credențialele de mail din Secret
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: MAIL_USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: MAIL_PASS

    
